[tool.poetry]
name = "repl_python3_Python-1"
version = "0.1.0"
description = ""
authors = ["modleo <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
SQLAlchemy = "^1.4.25"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
